apiVersion: v1
kind: Service
metadata:
  name: maven-hello-world-service-nodeport # name of the service

spec:
  type: NodePort # Used for accessing a port externally
  ports:
    - port: 9004 # Service port
      targetPort: 8080 # Pod port, default: same as port
      nodePort: 30001 # Node port which can be used externally, default: auto-assign any free port
  selector: # Which pods to expose externally ?
    app: maven-hello-world
    tier: frontend
